package net.jfun.legato.util;

public class BASIC_FN {
    public static byte[] F00 = new byte[]{
            (byte) 0xFD,
            (byte) 0xFD,
            (byte) 0x00,
            (byte) 0x00,
            (byte) 0x07,
            (byte) 0xE4,
            (byte) 0x3C,
            (byte) 0x3C,
            (byte) 0x44,
            (byte) 0x44,
            (byte) 0x03,
            (byte) 0xE8,
            (byte) 0x01,
            (byte) 0x09,
            (byte) 0xFE,
            (byte) 0xFE
    };
    public static byte[] F01 = new byte[]{
            (byte) 0xFD,
            (byte) 0xFD,
            (byte) 0x00,
            (byte) 0x01,
            (byte) 0x07,
            (byte) 0x24,
            (byte) 0x19,
            (byte) 0x19,
            (byte) 0x14,
            (byte) 0x14,
            (byte) 0x00,
            (byte) 0x00,
            (byte) 0x01,
            (byte) 0x23,
            (byte) 0xFE,
            (byte) 0xFE
    };
    public static byte[] F02 = new byte[]{
            (byte) 0xFD,
            (byte) 0xFD,
            (byte) 0x00,
            (byte) 0x02,
            (byte) 0x07,
            (byte) 0x24,
            (byte) 0x19,
            (byte) 0x19,
            (byte) 0x14,
            (byte) 0x14,
            (byte) 0x00,
            (byte) 0x00,
            (byte) 0x01,
            (byte) 0x22,
            (byte) 0xFE,
            (byte) 0xFE
    };
    public static byte[] F03 = new byte[]{
            (byte) 0xFD,
            (byte) 0xFD,
            (byte) 0x00,
            (byte) 0x03,
            (byte) 0x07,
            (byte) 0x24,
            (byte) 0x19,
            (byte) 0x19,
            (byte) 0x14,
            (byte) 0x14,
            (byte) 0x00,
            (byte) 0x00,
            (byte) 0x01,
            (byte) 0x21,
            (byte) 0xFE,
            (byte) 0xFE
    };
    public static byte[] F04 = new byte[]{
            (byte) 0xFD,
            (byte) 0xFD,
            (byte) 0x00,
            (byte) 0x04,
            (byte) 0x07,
            (byte) 0xF3,
            (byte) 0x19,
            (byte) 0x19,
            (byte) 0x14,
            (byte) 0x14,
            (byte) 0x00,
            (byte) 0x00,
            (byte) 0x01,
            (byte) 0xF1,
            (byte) 0xFE,
            (byte) 0xFE
    };
    public static byte[] F05 = new byte[]{
            (byte) 0xFD,
            (byte) 0xFD,
            (byte) 0x00,
            (byte) 0x05,
            (byte) 0x07,
            (byte) 0xF3,
            (byte) 0x14,
            (byte) 0x14,
            (byte) 0x0F,
            (byte) 0x0F,
            (byte) 0x00,
            (byte) 0x00,
            (byte) 0x01,
            (byte) 0xF2,
            (byte) 0xFE,
            (byte) 0xFE
    };
    public static byte[] F06 = new byte[]{
            (byte) 0xFD,
            (byte) 0xFD,
            (byte) 0x00,
            (byte) 0x06,
            (byte) 0x07,
            (byte) 0xF3,
            (byte) 0x14,
            (byte) 0x14,
            (byte) 0x0F,
            (byte) 0x0F,
            (byte) 0x00,
            (byte) 0x00,
            (byte) 0x01,
            (byte) 0xF3,
            (byte) 0xFE,
            (byte) 0xFE
    };
    public static byte[] F07 = new byte[]{
            (byte) 0xFD,
            (byte) 0xFD,
            (byte) 0x00,
            (byte) 0x07,
            (byte) 0x07,
            (byte) 0xF3,
            (byte) 0x14,
            (byte) 0x14,
            (byte) 0x0F,
            (byte) 0x0F,
            (byte) 0x00,
            (byte) 0x00,
            (byte) 0x01,
            (byte) 0xF4,
            (byte) 0xFE,
            (byte) 0xFE
    };
    public static byte[] F08 = new byte[]{
            (byte) 0xFD,
            (byte) 0xFD,
            (byte) 0x00,
            (byte) 0x08,
            (byte) 0x07,
            (byte) 0xF8,
            (byte) 0x14,
            (byte) 0x0F,
            (byte) 0x0F,
            (byte) 0x0F,
            (byte) 0x00,
            (byte) 0x00,
            (byte) 0x01,
            (byte) 0xED,
            (byte) 0xFE,
            (byte) 0xFE
    };
    public static byte[] F09 = new byte[]{
            (byte) 0xFD,
            (byte) 0xFD,
            (byte) 0x00,
            (byte) 0x09,
            (byte) 0x07,
            (byte) 0xF8,
            (byte) 0x14,
            (byte) 0x0F,
            (byte) 0x0F,
            (byte) 0x0F,
            (byte) 0x00,
            (byte) 0x00,
            (byte) 0x01,
            (byte) 0xEF,
            (byte) 0xFE,
            (byte) 0xFE
    };
    public static byte[] F10 = new byte[]{
            (byte) 0xFD,
            (byte) 0xFD,
            (byte) 0x00,
            (byte) 0x10,
            (byte) 0x07,
            (byte) 0xF8,
            (byte) 0x14,
            (byte) 0x0F,
            (byte) 0x0F,
            (byte) 0x0F,
            (byte) 0x00,
            (byte) 0x00,
            (byte) 0x01,
            (byte) 0xF5,
            (byte) 0xFE,
            (byte) 0xFE
    };
    public static byte[] F11 = new byte[]{
            (byte) 0xFD,
            (byte) 0xFD,
            (byte) 0x00,
            (byte) 0x11,
            (byte) 0x07,
            (byte) 0xF8,
            (byte) 0x14,
            (byte) 0x0F,
            (byte) 0x0F,
            (byte) 0x0F,
            (byte) 0x00,
            (byte) 0x00,
            (byte) 0x01,
            (byte) 0xF6,
            (byte) 0xFE,
            (byte) 0xFE
    };
    public static byte[] F12 = new byte[]{
            (byte) 0xFD,
            (byte) 0xFD,
            (byte) 0x00,
            (byte) 0x12,
            (byte) 0x07,
            (byte) 0xFD,
            (byte) 0x14,
            (byte) 0x0F,
            (byte) 0x0F,
            (byte) 0x0F,
            (byte) 0x00,
            (byte) 0x00,
            (byte) 0x01,
            (byte) 0xF7,
            (byte) 0xFE,
            (byte) 0xFE
    };
}
